# Pipeline Configuration
# This file defines the sequence of tasks and their parameters

# List of tasks to execute in order
tasks:
  - name: optimize
    task_type: image_optimization  # Registry name
    params:
      target_width: 1920                    # Output resolution (maintains aspect ratio)
      min_area_ratio: 0.10                  # Flipchart must be at least 10% of image
      max_area_ratio: 0.95                  # Avoid detecting entire image
      enable_perspective_correction: true   # Enable for angled shots

  - name: upload
    task_type: upload  # Registry name
    params:
      uploader: "@nvidia_uploader"  # Reference to registered provider

  - name: ocr
    task_type: ocr  # Registry name
    params:
      provider: "@nvidia_ocr"  # Reference to registered provider

  - name: save
    task_type: save_pdf  # Registry name
    params:
      output_path: "combined.pdf"

# Global configuration
input_dir: "."
extension: ".jpg"
output_file: "combined.pdf"
enable_ocr: true
